# Thanks to
# https://github.com/deviantony/docker-elk/blob/master/docker-compose.yml
{
  "postgres": {
    "image": "kartoza/postgis:latest",
    "volumes": [
      "./postgres/postgresql.conf:/etc/postgresql/9.4/main/postgresql.conf",
      "./postgres/data:/var/lib/postgresql"  # commented to work on mac --
                                              # will cause persistence issues!!
    ],
    "ports": [
      "5432:5432"
    ],
    "privileged": true
  },
  #"kibana": {
  #  "build": "kibana/",
  #  "volumes": [
  #    "./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml"
  #  ],
  #  "ports": [
  #    "5601:5601"
  #  ],
  #  "links": [
  #    "elasticsearch"
  #  ],
  #},
  "elasticsearch": {
    "image": "elasticsearch:latest",
    "command": "elasticsearch -Des.network.host=0.0.0.0",
    #"volumes": [
    #  "./esconfig:/usr/share/elasticsearch/config"
    #],
    "ports": [
      "9200:9200",
      "9300:9300"
    ]
  },
  "browser": {
    "image": "nginx:latest",
    "volumes": [
      "./browser:/usr/share/nginx/html/:ro",
      "./browser/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    ],
   "links": [
     "elasticsearch"
   ],
   "ports": [
      "80:80"
   ]
  },
  "bigmetadata_daemon": {
    "build": ".",
    "links": [
      "elasticsearch",
      "postgres"
    ],
    "volumes": [
      ".:/bigmetadata"
    ],
    "ports": [
      "8082:8082"
    ],
    "environment": {
      "PYTHONPATH": "/bigmetadata",
      "ES_HOST": "elasticsearch",
      "ES_PORT": "9200",
      "PGHOST": "postgres",
      "PGUSER": "docker",
      "PGPASSWORD": "docker",
      "PGDATABASE": "gis"
    },
    "env_file": ".env"
  },
  "bigmetadata": {
    "build": ".",
    "links": [
      "bigmetadata_daemon",
      "elasticsearch",
      "postgres"
    ],
    "volumes": [
      ".:/bigmetadata"
    ],
    "environment": {
      "PYTHONPATH": "/bigmetadata",
      "ES_HOST": "elasticsearch",
      "ES_PORT": "9200",
      "PGHOST": "postgres",
      "PGUSER": "docker",
      "PGPASSWORD": "docker",
      "PGDATABASE": "gis"
    },
    "env_file": ".env"
  }
}
