# Thanks to
# https://github.com/deviantony/docker-elk/blob/master/docker-compose.yml
{
  "postgres": {
    "image": "carto/bigmetadata_postgres",
    "volumes": [
      "./postgres/data:/var/lib/postgresql",
      "./observatory-extension:/observatory-extension",
      "./dataservices-api:/dataservices-api",
      "./data-services:/data-services",
      "./cartodb-postgresql:/cartodb-postgresql",
      "./tmp:/bigmetadata/tmp"
    ],
    "environment": {
      "PGUSER": "docker",
      "PGPASSWORD": "docker",
      "PGDATABASE": "gis",
      "LC_ALL": "C.UTF-8",
      "LANG": "C.UTF-8"
    },
    "links": [
      "redis:localhost"
    ],
    "privileged": true,
    "ports": [
      "5554:5432"
    ]
  },
  "nginx": {
    "image": "nginx:latest",
    "volumes": [
      "./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro",
      "./catalog/build/html:/usr/share/nginx/html/catalog/:ro",
      "./docs/build/html:/usr/share/nginx/html/docs/:ro",
      "./perftest:/usr/share/nginx/html/perftest/:ro",
    ],
    "ports": [
       "80"
    ],
  },
  "bigmetadata_daemon": {
    "image": "carto/bigmetadata",
    "links": [
      "postgres"
    ],
    "volumes": [
      ".:/bigmetadata",
      "./crontab:/etc/cron.d/cron",
    ],
    "ports": [
      "8082"
    ],
    "environment": {
      "PYTHONPATH": "/bigmetadata",
      "PGHOST": "postgres",
      "PGUSER": "docker",
      "PGPASSWORD": "docker",
      "PGDATABASE": "gis",
      "LC_ALL": "C.UTF-8",
      "LANG": "C.UTF-8",
      "LUIGI_CONFIG_PATH": "/bigmetadata/conf/luigi_daemon.cfg",
    },
    "env_file": ".env",
    "command": "/bin/bash -c 'while : ; do pg_isready -t 1 && break; done && cron && crontab ./crontab && luigid'"
  },
  "bigmetadata": {
    "image": "carto/bigmetadata",
    "links": [
      "postgres",
      "bigmetadata_daemon",
    ],
    "volumes": [
      ".:/bigmetadata"
    ],
    "security_opt": [
      "seccomp:unconfined"
    ],
    "cap_add": [
      "SYS_PTRACE"
    ],
    "environment": {
      "PYTHONPATH": "/bigmetadata",
      "PGHOST": "postgres",
      "PGUSER": "docker",
      "PGPASSWORD": "docker",
      "PGDATABASE": "gis",
      "LC_ALL": "C.UTF-8",
      "LANG": "C.UTF-8",
      "LUIGI_CONFIG_PATH": "/bigmetadata/conf/luigi_client.cfg",
    },
    "env_file": ".env",
    "stdin_open": true,
    "tty": true
  },
  "ipython": {
    "build": "ipython",
    "ports": [
      "8888"
    ],
    "links": [
      "bigmetadata_daemon",
      "postgres"
    ],
    "volumes": [
      ".:/bigmetadata"
    ],
    "environment": {
      "PYTHONPATH": "/bigmetadata",
      "PGHOST": "postgres",
      "PGUSER": "docker",
      "PGPASSWORD": "docker",
      "PGDATABASE": "test",
      "LC_ALL": "C.UTF-8",
      "LANG": "C.UTF-8"
    },
    "env_file": ".env",
    "working_dir": "/tmp/ipython",
    "command": "sh -c /bigmetadata/ipython/start.sh"
  },
  "redis": {
    "image": "redis",
    "ports": [
      "6379"
    ]
  },
}
