version: '3.1'
services:
  postgres:
    image: carto/bigmetadata_postgres
    volumes:
      - ${DO_LOCAL_POSTGRESQL_LIB_DIR:-./postgres/data}:/var/lib/postgresql
      - ./observatory-extension:/observatory-extension
      - ./dataservices-api:/dataservices-api
      - ./data-services:/data-services
      - ./cartodb-postgresql:/cartodb-postgresql
      - ${DO_LOCAL_POSTGRESQL_TMP_DIR:-./tmp}:/bigmetadata/tmp
    environment:
      PGUSER: docker
      PGPASSWORD: docker
      PGDATABASE: gis
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      ALLOW_IP_RANGE: '172.0.0.0/8'
    privileged: true
    ports:
      - 5554:5432
    env_file: .env

  postgres10:
    image: carto/bigmetadata_postgres_10
    volumes:
      - ${DO_LOCAL_POSTGRESQL_10_LIB_DIR:-./postgres/data}:/var/lib/postgresql
      - ./observatory-extension:/observatory-extension
      - ./dataservices-api:/dataservices-api
      - ./data-services:/data-services
      - ./cartodb-postgresql:/cartodb-postgresql
      - ${DO_LOCAL_POSTGRESQL_10_TMP_DIR:-./tmp}:/bigmetadata/tmp
    environment:
      PGDATA: /var/lib/postgresql/pg_data
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gis
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    privileged: true
    ports:
      - 5554:5432
    env_file: .env

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./catalog/build/html:/usr/share/nginx/html/catalog/:ro
      - ./docs/build/html:/usr/share/nginx/html/docs/:ro
      - ./perftest:/usr/share/nginx/html/perftest/:ro
    ports:
      - 80

  bigmetadata_daemon:
    image: carto/bigmetadata
    volumes:
      - .:/bigmetadata
    ports:
      - 8082
    depends_on:
      - postgres
    environment:
      PYTHONPATH: /bigmetadata
      PGHOST: postgres
      PGUSER: docker
      PGPASSWORD: docker
      PGDATABASE: gis
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      LUIGI_CONFIG_PATH: /bigmetadata/conf/luigi_daemon.cfg
      LOGGING_CONFIG_PATH: /bigmetadata/conf/logging_daemon.cfg
      LOGGING_FILE: etl_daemon.log
    env_file: .env
    command: "/bin/bash -c 'while : ; do pg_isready -t 1 && break; done && luigid'"

  bigmetadata:
    image: carto/bigmetadata
    volumes:
      - .:/bigmetadata
    depends_on:
      - postgres
      - bigmetadata_daemon
    entrypoint: /bigmetadata/conf/client_entrypoint.sh
    environment:
      PYTHONPATH: '/bigmetadata'
      PGHOST: postgres
      PGUSER: docker
      PGPASSWORD: docker
      PGDATABASE: gis
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      LUIGI_CONFIG_PATH: /opt/bigmetadata/etc/luigi_client.cfg
      LOGGING_CONFIG_PATH: /opt/bigmetadata/etc/logging_client.cfg
    env_file: .env
    stdin_open: true
    tty: true
